export const questionBank = [
  { id: 1, text: "O Estado deve ser o principal provedor de serviços essenciais (saúde, educação).", orientation: -1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 2, text: "Privatizações são, em geral, o melhor caminho para melhorar a eficiência de serviços.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 3, text: "Leis trabalhistas devem ser flexibilizadas para facilitar contratações.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 4, text: "Programas de transferência de renda devem ser ampliados mesmo com aumento de impostos.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 5, text: "Cotas e políticas afirmativas são necessárias para corrigir desigualdades históricas.", orientation: -1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 6, text: "O porte de armas pelo cidadão comum aumenta a segurança.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 7, text: "A proteção ambiental deve limitar projetos econômicos quando houver risco significativo.", orientation: -1, source: "https://www.brasildefato.com.br/2022/07/07/marcio-astrini-a-extrema-direita-tem-no-meio-ambiente-um-inimigo-e-a-esquerda-no-brasil-nao-se-dispensa" },
  { id: 8, text: "Menos impostos em geral geram mais crescimento mesmo com menos Estado.", orientation: +1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 9, text: "O casamento igualitário e direitos LGBT+ devem ser garantidos por lei.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 10, text: "A escola deve focar conteúdos tradicionais e evitar temas políticos e sociais em sala.", orientation: +1, source: "https://jornal.usp.br/universidade/escola-sem-partido-reflete-discurso-conservador-na-educacao/" },
  { id: 11, text: "Tributação sobre grandes fortunas é desejável para financiar serviços públicos.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 12, text: "Empresas devem ter menos burocracia mesmo que alguma proteção ao trabalhador diminua.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 13, text: "Povos indígenas devem ter prioridade na demarcação e proteção de terras.", orientation: -1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 14, text: "A redução do papel do Estado é positiva na maioria dos setores.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 15, text: "Descriminalizar o uso de drogas é melhor que endurecer punições.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 16, text: "A punição mais dura é o caminho principal para reduzir a criminalidade.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 17, text: "Subsídios estatais para setores estratégicos são importantes para o desenvolvimento.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 18, text: "Livre mercado aloca recursos melhor do que o governo na maioria dos casos.", orientation: +1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 19, text: "Imigrantes devem ter facilidades para viver e trabalhar no país.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 20, text: "Valores tradicionais devem orientar políticas públicas.", orientation: +1, source: "https://www.diferenca.com/diferencas-entre-esquerda-direita-conservador-liberal/" },
  { id: 21, text: "Greves e sindicatos são ferramentas importantes de equilíbrio nas relações de trabalho.", orientation: -1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 22, text: "Reduzir benefícios sociais incentiva as pessoas a buscarem emprego.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 23, text: "O Estado deve regular fortemente bancos e grandes empresas para evitar abusos.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 24, text: "Empreender deve ser o mais simples possível, mesmo que isso reduza certas exigências.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 25, text: "O Estado deve ser forte, realizando investimentos e controlando a economia para reduzir desigualdades e garantir bem-estar social.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 26, text: "Impostos altos sobre os mais ricos são necessários para financiar o bem-estar e os serviços públicos.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 27, text: "O Estado deve garantir igualdade de oportunidades, atuando como agente principal no desenvolvimento social.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 28, text: "Empresas e bancos precisam de maior regulamentação e de uma tributação mais elevada para evitar abusos e reduzir desigualdades.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 29, text: "O acesso à saúde é um direito fundamental que deve ser garantido e financiado pelo Estado.", orientation: -1, source: "https://brasilescola.uol.com.br/politica/direita-esquerda.htm" },
  { id: 30, text: "Políticas de planejamento familiar, legalização do aborto e apoio à pesquisa com células-tronco devem ser adotadas pelo governo.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 31, text: "Direitos LGBTQIA+, incluindo casamento igualitário e leis anti-discriminatórias, devem ser plenamente reconhecidos.", orientation: -1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 32, text: "O Estado deve ser reduzido ao mínimo, limitando-se a garantir a ordem pública e deixando a economia se regular pela livre concorrência.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 33, text: "Os impostos devem ser pequenos ou até inexistentes para incentivar a livre iniciativa e o crescimento econômico.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 34, text: "É melhor reduzir o tamanho do governo e extinguir programas assistenciais, pois o mercado é mais eficiente na alocação de recursos.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 35, text: "Empresas devem ter menos regulação e impostos mais baixos para crescer e gerar riqueza.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 36, text: "Programas públicos de saúde não devem ser ampliados; a iniciativa privada deve ser priorizada.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 37, text: "A legalização do aborto e a pesquisa com células-tronco devem ser restritas por violarem valores tradicionais.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
  { id: 38, text: "Avanços nos direitos LGBTQIA+ devem ser limitados, pois contrariam valores tradicionais.", orientation: +1, source: "https://www.diferenca.com/esquerda-e-direita-na-politica/" },
];

